[package]
name = "reasoning"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = {version="4.5.49", features = ["derive"]}
rand = "0.9.2"
serde = {version = "1.0.228", features = ["derive"]}
serde_json = "1.0.145"

